language: php

matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      env: PHPUNITVER=5.7
    - php: 7.0
      env: PHPUNITVER=5.7
    - php: 7.1
      env: PHPUNITVER=5.7
    - php: hhvm-3.21
      env: PHPUNITVER=5.7 HHVM=true
    - php: hhvm-3.24
      env: PHPUNITVER=5.7 HHVM=true
#  allow_failures:
#    - php: hhvm-3.21
#    - php: hhvm-3.24

before_install:
  - composer install
  - if [ $PHPUNITVER"x" != "x" ]; then mkdir -p ./vendor/bin; curl -sSfL -o ./vendor/bin/phpunit https://phar.phpunit.de/phpunit-$PHPUNITVER.phar; chmod u+x ./vendor/bin/phpunit; fi

script:
  - if [ $PHPUNITVER"x" != "x" ]; then ./vendor/bin/phpunit .; else phpunit .; fi

sudo: false
