language: php

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm
      env: HHVM=true
  allow_failures:
    - php: hhvm

before_install:
  - composer install
#  - if [[ $HHVM == true ]]; then composer require "phpunit/phpunit:5.7"; fi

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

#script:
#  - if [[ $HHVM == true ]]; then ./vendor/bin/phpunit .; else phpunit .; fi

sudo: false
